### ISSUE TITLE
Refactor opensim-gui to use the opensim-viewer codebase underneath

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-viewer#117]
While we can use the javascript code as is to display the  static viewer inside the opensim-gui work need to be done to explore:

1. Using gltf in memory to communicate with the viewer
2. 2-way communication with the viewer (as needed by the edit functionality)
3. Handle off-line operation without backend and possibly no python connection

**Comment by aymanhab** [comment]
There's support to run ReactApp and access it using websockets, the specifics for the openim-viewer and the opensim-gui need to be ironed out. The pros of this approach:
1. Lighter coupling between the gui and the viewer 
2. Ease of upgrading and integrating other third party tools that are React based.

**Comment by aymanhab** [comment]
This issue should be converted to an epic that spans multi-sprints per the dev team plans/presentations:

- [ ] Deploy opensim-viewer application and load into GUI without model(s)
- [ ] Customize viewer to remove items that don't belong in application (login, gallery, toolbar,...)
- [ ] Add options in viewer to parallel/enhance the menu in application/GUI
- [ ] Add websocket layer around viewer code base and test two way communications
- [ ] Convert GUI code to create and pass gltf scene instead of old format
- [ ] Remove GUI animation slider and animate in browser
- [ ] Wire editing to viewer
- [ ] Implement muscles.

**Comment by aymanhab** [comment]
issue #134

**Comment by aymanhab** [comment]
With the latest GUI/viewer combo, the GUI create json file from a model that successfully loads into the embedded viewer. Remaining items for a fully functional embedded viewer:
- [ ] distinguish files that contain full scenes (gltf) from those containing groups of objects (json)
- [ ] Support Model add/remove/offset to enable multiple models in viewer
- [ ] Support commands used to communicate messages from GUI to viewer (12)
- [ ] Send mocap data as animations
- [ ] Wire animation slider to viewer animation clips mixer
- [ ] Handle muscles.

**Comment by aymanhab** [comment]
Per latest status/demo here are the remaining loose ends to fully functional viewer embedded in GUI:
- [ ] selection and dragging, passback values to model (marker/muscle editing)
- [ ] Manage model offsets and experimental data without offsets
- [ ] Support sync. motions behavior
- [ ] Color/lights default to 4.5 look
- [ ] Add watermark
- [ ] redo Snapshot with arbitrary resolution
- [ ] save/restore environments (camera, lights, floor, ...)
- [ ]

**Comment by aymanhab** [comment]
Move individual remaining tasks to either separate issues or to the epic for unifying viewer with gui

**Comment by aymanhab** [comment]
This umbrella issue can be closed
